cache: apt
sudo: false

file:
  - tests/*

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev

# blocklist
# Block all /*feature*/ branches
# Anything within /_>/ is treated as a Regex
branches:
  except:
  - /*feature*/

# safelist
# Only Build and Test changes of the master branch
branches:
  only:
  - new_version

before_install:
 - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda update --yes conda

install:
 - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
 - source activate test
 - conda install --yes numpy scipy matplotlib pip nose
 - pip install setuptools
 - python setup.py install
 - pip install coveralls

script: coverage run test.py tests/*

after_success:
 coveralls
